[project]
name = "serverwatcher"
version = "0.1.0"
description = "Contains backend code for the an IoT server monitoring device"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.125.0",
    "influxdb3-python>=0.16.0",
    "pandas>=3.0.0",
    "passlib>=1.7.4",
    "pydantic>=2.12.5",
    "python-jose>=3.5.0",
    "requests>=2.32.5",
    "smtpemail>=0.4.2",
    "uvicorn[standard]>=0.38.0",
]
